---
title: "Documentation in Theradoc"
date: 'Updated on `r format(max(file.info(list.files("../data/raw", pattern = "resident_general", full.names = TRUE))$mtime), "%B %d, %Y")`'
output: 
  pdf_document: 
    latex_engine: xelatex
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# source("../src/1-preprocess.R")
```

```{r data, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(forcats)
library(stringr)
library(themebg)
library(grid)
library(gridExtra)

data_ext <- "../data/raw"
# data_tidy <- "../data/tidy/"

clin_cols <- c(rep("text", 7), "date", "text", "text", "numeric", rep("text", 8), rep("numeric", 5))

data_clin <- list.files(data_ext, pattern = "resident_clinical", full.names = TRUE) %>%
    map_df(read_excel, col_types = clin_cols) %>%
    mutate_at("Age", str_replace_all, pattern = " Y", replacement = "") %>%
    mutate_at("Age", as.numeric) %>%
    select(resident = User,
           fin = `Account Number`,
           age = Age,
           provider = `Receiving Clinician`,
           rec_datetime = `Date Entered`,
           rec_type = `Intervention Type`,
           rec_location = `Intervention Location`,
           time_spent = `Time Spent (in minutes)`,
           alert_num = `Related Alert`,
           alert_name = `Alert Title`,
           activity = `Clinical Activities`,
           follow_up = `Follow-up Status`,
           status = `Intervention Status`,
           rec_savings = `Intervention Savings`,
           total_costs = `Total Cost`,
           total_savings = `Total Savings`,
           other_costs = `Other Costs`,
           other_savings = `Other Savings`) %>%
    mutate_at("activity", str_replace_all, pattern = " \\(prevent order, discontinue, change\\)", replacement = "") %>%
    separate(activity, c("act1", "act2", "act3", "act4", "act5", "act6"), sep = ",", remove = FALSE) %>%
    mutate_at("resident", str_to_title) %>%
    mutate(day_week = wday(rec_datetime, TRUE),
           weekday = !(wday(rec_datetime, TRUE) %in% c("Sat", "Sun")),
           rec_week = if_else(wday(rec_datetime, TRUE) == "Sun", floor_date(rec_datetime, "week") - days(6), floor_date(rec_datetime, "week") + days(1)),
           rec_month = floor_date(rec_datetime, "month"),
           rec_quarter = floor_date(rec_datetime, "quarter"))

gen_cols <- c(rep("text", 7), "date", "text", "text", "numeric", rep("text", 10), rep("numeric", 5))

data_gen <- list.files(data_ext, pattern = "resident_general", full.names = TRUE) %>%
    map_df(read_excel, col_types = gen_cols) %>%
    mutate_at("Age", str_replace_all, pattern = " Y", replacement = "") %>%
    mutate_at("Age", as.numeric) %>%
    select(resident = User,
           fin = `Account Number`,
           age = Age,
           provider = `Receiving Clinician`,
           rec_datetime = `Date Entered`,
           rec_type = `Intervention Type`,
           rec_location = `Intervention Location`,
           time_spent = `Time Spent (in minutes)`,
           alert_num = `Related Alert`,
           alert_name = `Alert Title`,
           reason = Reasons,
           comment = `Team Comments`,
           follow_up = `Follow-up Status`,
           status = `Intervention Status`,
           rec_savings = `Intervention Savings`,
           total_costs = `Total Cost`,
           total_savings = `Total Savings`,
           other_costs = `Other Costs`,
           other_savings = `Other Savings`) %>%
    mutate_at("reason", str_replace_all, pattern = " \\(renal/hepatic, etc.\\)", replacement = "") %>%
    separate(reason, c("reason1", "reason2", "reason3", "reason4", "reason5", "reason6"), sep = ",", remove = FALSE) %>%
    mutate_at("resident", str_to_title) %>%
    mutate(day_week = wday(rec_datetime, TRUE),
           weekday = !(wday(rec_datetime, TRUE) %in% c("Sat", "Sun")),
           rec_week = if_else(wday(rec_datetime, TRUE) == "Sun", floor_date(rec_datetime, "week") - days(6), floor_date(rec_datetime, "week") + days(1)),
           rec_month = floor_date(rec_datetime, "month"),
           rec_quarter = floor_date(rec_datetime, "quarter"))

sepsis <- c("Initiate Antimicrobials", 
            "Change Current Antimicrobial(s)", 
            "Change Antimicrobial Dose or Route",
            "Fluid Resuscitation",
            "Lab or Micro Test Recommended",
            "No Intervention Required")

res <- data_frame(resident = c("Doyle, Meagan", "Kim, Sara", "Procopio, Vincent", "Moore, Megan", "Lai, Wei", "Leung, Helen", "Stephenson, Elizabeth", "Nguyen, Steffany", "Szymanski, Tom"))

cur_month = mdy("6/1/2018")
cur_quarter = mdy("4/1/2018")
```

```{r good_catches, fig.width=7, fig.height=5, fig.lp='', fig.align='center'}
qtd <- data_gen %>%
    filter(rec_quarter == cur_quarter) %>%
    count(resident, sort = TRUE) %>%
    full_join(res, by = "resident") %>%
    mutate_at("resident", as_factor) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

qtd_alert <- qtd %>%
    mutate(flag = n == 0) %>%
    filter(flag)

mtd <- data_gen %>%
    filter(rec_month == cur_month) %>%
    count(resident, weekday, sort = TRUE) %>%
    full_join(res, by = "resident") %>%
    mutate_at("resident", factor, levels = levels(qtd$resident)) %>%
    mutate_at("n", funs(coalesce(., as.integer(0)))) %>%
    mutate_at("weekday", funs(coalesce(., FALSE)))

prev_month <- data_gen %>%
    filter(rec_month == cur_month - months(1)) %>%
    count(resident, sort = TRUE) %>%
    full_join(res, by = "resident") %>%
    mutate_at("resident", factor, levels = levels(qtd$resident)) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

g <- ggplot() +
    geom_bar(aes(x = resident, y = n, fill = weekday), data = mtd, stat = "identity", width = 0.5) +
    geom_point(aes(x = resident, y = n), data = prev_month, shape = 4, size = 2) +
    geom_errorbar(aes(x = resident, ymin = 5, ymax = 5), data = mtd, width = 0.3, size = 0.75) +
    geom_text(aes(x = resident, y = -0.5, label = n), data = qtd, size = 3.25) +
    annotate("text", x = 11, y = -0.5, label = "QTD", size = 3.25, color = "grey35") +
    annotate("text", x = 11, y = 5, label = "Target", size = 3.25, color = "grey35")

if (nrow(qtd_alert) > 0) {
    g <- g +
        geom_point(aes(x = resident, y = -1), data = qtd_alert, shape = 19, color = "black")
}

g <- g +
    expand_limits(x = 12) +
    ggtitle("Good Catches for Current Month-to-Date") +
    labs(caption = "QTD = Number for current Quarter-to-Date. X = Results for previous month.") +
    xlab(NULL) +
    ylab(NULL) +
    # scale_y_continuous("", labels = scales::comma_format(digits = 0)) +
    scale_fill_manual("", values = c("#bdbdbd", "#636363"), labels = c("Weekend", "Rotation")) +
    coord_flip() +
    theme_bg(xticks = FALSE, yticks = FALSE) +
    theme(axis.line = element_blank(), 
          legend.position = "bottom", 
          plot.title = element_text(hjust = 0.5, size = 10, color = "grey35"),
          axis.text.y = element_text(hjust = 0))

g
```

```{r sepsis}
qtd <- data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis,
           rec_quarter == cur_quarter) %>%
    count(resident, sort = TRUE) %>%
    # full_join(res, by = "resident") %>%
    mutate_at("resident", as_factor) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

prev_quarter <- data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis,
           rec_quarter == cur_quarter - months(3)) %>%
    count(resident, sort = TRUE) %>%
    # full_join(res, by = "resident") %>%
    mutate_at("resident", factor, levels = levels(qtd$resident)) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

sepsis_plot <- ggplot() +
    geom_bar(aes(x = resident, y = n), data = qtd, stat = "identity", width = 0.5, fill = "#636363") +
    geom_point(aes(x = resident, y = n), data = prev_quarter, shape = 4, size = 2) +
    ggtitle("Sepsis Alerts for Quarter-to-Date") +
    # labs(caption = "X = Results for previous quarter.") +
    xlab(NULL) +
    ylab(NULL) +
    coord_flip() +
    theme_bg(xticks = FALSE, yticks = FALSE) +
    theme(axis.line = element_blank(), 
          legend.position = "bottom", 
          plot.title = element_text(hjust = 0.5, size = 10, color = "grey35"),
          axis.text.y = element_text(hjust = 0))
```

```{r sepsis_interventions}
sepsis_interventions <- data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis) %>%
    mutate_at("activity", fct_infreq) %>%
    mutate_at("activity", fct_rev) %>%
    ggplot(aes(x = activity)) +
    geom_bar(fill = "#636363") +
    xlab(NULL) +
    ylab(NULL) +
    coord_flip() +
    theme_bg(yticks = FALSE)
```

```{r sepsis_weekly}
sepsis_weekly <- data_clin %>%
    filter(rec_week >= ymd("2017-07-24")) %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis) %>%
    count(rec_week) %>%
    ggplot(aes(x = rec_week, y = n)) +
    geom_line() +
    geom_smooth(method = "lm", color = "grey35") +
    ggtitle("Sepsis Alerts by Week") +
    xlab(NULL) +
    ylab(NULL) +
    scale_x_datetime(date_breaks = "2 weeks", date_labels = "%m/%d") +
    theme_bg() +
    theme(plot.title = element_text(hjust = 0.5, size = 10, color = "grey35"))
```

```{r sepsis_dayweek}
sepsis_dayweek <- data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis) %>%
    count(day_week) %>%
    spread(day_week, n, fill = 0, drop = FALSE) %>%
    gather(day_week, n, Sun:Sat) %>%
    mutate_at("day_week", fct_inorder) %>%
    # mutate_at("day_week", factor, ordered = TRUE, levels = levels(data_clin$day_week)) %>%
    ggplot(aes(x = day_week, y = n)) +
    geom_bar(stat = "identity", fill = "#636363") +
    ggtitle("Sepsis Alerts by Day of Week") +
    xlab(NULL) +
    ylab(NULL) +
    theme_bg(xticks = FALSE) +
    theme(plot.title = element_text(hjust = 0.5, size = 10, color = "grey35"))
```

```{r oncall}
qtd <- data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity == "Resident On-Call",
           rec_quarter == cur_quarter) %>%
    count(resident, sort = TRUE) %>%
    # full_join(res, by = "resident") %>%
    mutate_at("resident", as_factor) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

prev_quarter <- data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity == "Resident On-Call",
           rec_quarter == cur_quarter - months(3)) %>%
    count(resident, sort = TRUE) %>%
    # full_join(res, by = "resident") %>%
    mutate_at("resident", factor, levels = levels(qtd$resident)) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

oncall_plot <- ggplot() +
    geom_bar(aes(x = resident, y = n), data = qtd, stat = "identity", width = 0.5, fill = "#636363") +
    geom_point(aes(x = resident, y = n), data = prev_quarter, shape = 4, size = 2) +
    ggtitle("On-Call Questions for Quarter-to-Date") +
    # labs(caption = "X = Results for previous quarter.") +
    xlab(NULL) +
    ylab(NULL) +
    coord_flip() +
    theme_bg(xticks = FALSE, yticks = FALSE) +
    theme(axis.line = element_blank(), 
          legend.position = "bottom", 
          plot.title = element_text(hjust = 0.5, size = 10, color = "grey35"),
          axis.text.y = element_text(hjust = 0))
```

```{r oncall_dayweek}
oncall_dayweek <- data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity == "Resident On-Call") %>%
    count(day_week) %>%
    spread(day_week, n, fill = 0, drop = FALSE) %>%
    gather(day_week, n, Sun:Sat) %>%
    mutate_at("day_week", fct_inorder) %>%
    ggplot(aes(x = day_week, y = n)) +
    geom_bar(stat = "identity", fill = "#636363") +
    ggtitle("On-Call Questions by Day of Week") +
    xlab(NULL) +
    ylab(NULL) +
    theme_bg(xticks = FALSE) +
    theme(plot.title = element_text(hjust = 0.5, size = 10, color = "grey35"))
```

```{r oncall_weekly}
oncall_weekly <- data_clin %>%
    filter(rec_week >= ymd("2017-07-24")) %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity == "Resident On-Call") %>%
    count(rec_week) %>%
    ggplot(aes(x = rec_week, y = n)) +
    geom_line() +
    geom_smooth(method = "lm", color = "grey35") +
    ggtitle("On-Call Questions by Week") +
    xlab(NULL) +
    ylab(NULL) +
    scale_x_datetime(date_breaks = "2 weeks", date_labels = "%m/%d") +
    theme_bg() +
    theme(plot.title = element_text(hjust = 0.5, size = 10, color = "grey35"))
```

```{r clinical, fig.width=8, fig.height=5, fig.align='center'}
grid.arrange(sepsis_plot, oncall_plot, sepsis_weekly, oncall_weekly, ncol = 2)
```

