---
title: "Exploring Resident Theradoc Documentation"
author: "Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
        toc: yes
        toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(forcats)
library(stringr)
library(themebg)

data_clin <- readRDS("../data/tidy/resident_clinical.Rds") %>%
    mutate_at("resident", str_to_title) %>%
    mutate(day_week = wday(rec_datetime, TRUE),
           weekday = !(wday(rec_datetime, TRUE) %in% c("Sat", "Sun")),
           rec_week = if_else(wday(rec_datetime, TRUE) == "Sun", floor_date(rec_datetime, "week") - days(6), floor_date(rec_datetime, "week") + days(1)),
           rec_month = floor_date(rec_datetime, "month"),
           rec_quarter = floor_date(rec_datetime, "quarter"))

data_gen <- readRDS("../data/tidy/resident_general.Rds") %>%
    mutate_at("resident", str_to_title) %>%
    mutate(day_week = wday(rec_datetime, TRUE),
           weekday = !(wday(rec_datetime, TRUE) %in% c("Sat", "Sun")),
           rec_week = if_else(wday(rec_datetime, TRUE) == "Sun", floor_date(rec_datetime, "week") - days(6), floor_date(rec_datetime, "week") + days(1)),
           rec_month = floor_date(rec_datetime, "month"),
           rec_quarter = floor_date(rec_datetime, "quarter"))

sepsis <- c("Initiate Antimicrobials", 
            "Change Current Antimicrobial(s)", 
            "Change Antimicrobial Dose or Route",
            "Fluid Resuscitation",
            "Lab or Micro Test Recommended",
            "No Intervention Required")

x.text <- element_text(angle = 45, hjust = 1, size = 6)

cur_month = mdy("8/1/2017")
cur_quarter = mdy("7/1/2017")
```

# Clinical Activity
```{r, fig.cap="Total number of clinical activities documented"}
data_clin %>%
    mutate_at("resident", fct_infreq) %>%
    mutate_at("resident", fct_rev) %>%
    ggplot(aes(x = resident)) +
    geom_bar() +
    coord_flip() +
    theme_bg(yticks = FALSE) 
```

```{r, fig.cap="Number of interventions documented by week"}
data_clin %>%
    count(rec_week) %>%
    ggplot(aes(x = rec_week, y = n)) +
    geom_line() +
    theme_bg()
```

```{r, fig.cap="Number of interventions documented by resident per month"}
data_clin %>%
    group_by(resident) %>%
    count(rec_month) %>%
    ggplot(aes(x = rec_month, y = n)) +
    geom_bar(stat = "identity") +
    facet_wrap(~ resident, ncol = 2) +
    theme_bg()
```

## Sepsis Alerts

```{r, fig.cap="Number of sepsis alerts documented by week"}
data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis) %>%
    count(rec_week) %>%
    ggplot(aes(x = rec_week, y = n)) +
    geom_line() +
    theme_bg()
```

```{r, fig.cap="Number of sepsis alerts documented by resident"}
data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis) %>%
    mutate_at("resident", fct_infreq) %>%
    mutate_at("resident", fct_rev) %>%
    ggplot(aes(x = resident)) +
    geom_bar() +
    coord_flip() +
    theme_bg(yticks = FALSE) 
```

```{r, fig.cap="Types of sepsis alert interventions"}
data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis) %>%
    mutate_at("activity", fct_infreq) %>%
    mutate_at("activity", fct_rev) %>%
    ggplot(aes(x = activity)) +
    geom_bar() +
    coord_flip() +
    theme_bg(yticks = FALSE)
```

```{r}
data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity %in% sepsis) %>%
    count(day_week) %>%
    ggplot(aes(x = day_week, y = n)) +
    geom_bar(stat = "identity") +
    theme_bg()
```


## On-Call Questions

```{r, fig.cap="Number of on-call questions documented by resident"}
data_clin %>%
    select(-activity) %>%
    gather(act_num, activity, act1:act6) %>%
    filter(activity == "Resident On-Call",
           rec_quarter == cur_quarter) %>%
    mutate_at("resident", str_to_title) %>%
    mutate_at("resident", fct_infreq) %>%
    mutate_at("resident", fct_rev) %>%
    ggplot(aes(x = resident)) +
    geom_bar(aes(fill = weekday), width = 0.5) +
    # geom_errorbar(aes(ymin = 5, ymax = 5), width = 0.25) +
    # geom_point(aes(y = previous), shape = 4, size = 2) +
    xlab("") +
    ylab("") +
    coord_flip() +
    theme_bg(xticks = FALSE, yticks = FALSE) +
    theme(axis.line = element_blank())
```

# Good Catches
```{r, fig.cap="Total number of general activities documented"}
data_gen %>%
    mutate_at("resident", fct_infreq) %>%
    mutate_at("resident", fct_rev) %>%
    ggplot(aes(x = resident)) +
    geom_bar() +
    coord_flip() +
    theme_bg(yticks = FALSE) 
```

```{r, fig.cap="Number of general activities documented by week"}
data_gen %>%
    count(rec_week) %>%
    ggplot(aes(x = rec_week, y = n)) +
    geom_line() +
    theme_bg()
```

```{r, fig.cap="Number of good catches documented by resident per month"}
data_gen %>%
    group_by(resident) %>%
    count(rec_month) %>%
    ggplot(aes(x = rec_month, y = n)) +
    geom_bar(stat = "identity") +
    facet_wrap(~ resident, ncol = 2) +
    theme_bg()
```

```{r, fig.cap="Number of rotation good catches documented by resident per month"}
data_gen %>%
    filter(weekday,
           rec_month >= mdy("8/1/2017")) %>%
    group_by(resident) %>%
    count(rec_month) %>%
    ggplot(aes(x = rec_month, y = n)) +
    geom_bar(stat = "identity") +
    facet_wrap(~ resident, ncol = 2) +
    theme_bg()
```

```{r, fig.cap="Number of rotation good catches documented by resident for current month"}
data_gen %>%
    filter(weekday,
           rec_month == cur_month | rec_month == cur_month - months(1)) %>%
    group_by(resident) %>%
    count(rec_month) %>%
    mutate(current = rec_month == cur_month) %>%
    ggplot(aes(x = rec_month, y = n)) +
    geom_bar(stat = "identity") +
    # scale_x_datetime("Month", breaks = c(cur_month - months(1), cur_month), labels = c("Last Month", "Current")) +
    facet_wrap(~ resident, ncol = 2) +
    theme_bg()
```

```{r, fig.cap="Number of good catches documented by each resident during the current month. The x indicates the number documented last month. The | indicates the target."}
res <- data_frame(resident = c("Doyle, Meagan", "Kim, Sara", "Procopio, Vincent", "Moore, Megan", "Lai, Wei", "Leung, Helen", "Stephenson, Elizabeth", "Nguyen, Steffany", "Szymanski, Tom", "Wilson, Lance"))

qtd <- data_gen %>%
    filter(rec_quarter == cur_quarter) %>%
    count(resident, sort = TRUE) %>%
    full_join(res, by = "resident") %>%
    mutate_at("resident", as_factor) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

mtd <- data_gen %>%
    filter(rec_month == cur_month) %>%
    count(resident, weekday, sort = TRUE) %>%
    full_join(res, by = "resident") %>%
    mutate_at("resident", factor, levels = levels(qtd$resident)) %>%
    mutate_at("n", funs(coalesce(., as.integer(0)))) %>%
    mutate_at("weekday", funs(coalesce(., FALSE)))

prev_month <- data_gen %>%
    filter(rec_month == cur_month - months(1)) %>%
    count(resident, sort = TRUE) %>%
    full_join(res, by = "resident") %>%
    mutate_at("resident", factor, levels = levels(qtd$resident)) %>%
    mutate_at("n", funs(coalesce(., as.integer(0))))

ggplot() +
    geom_bar(aes(x = resident, y = n, fill = weekday), data = mtd, stat = "identity", width = 0.5) +
    geom_point(aes(x = resident, y = n), data = prev_month, shape = 4, size = 2) +
    geom_errorbar(aes(x = resident, ymin = 5, ymax = 5), data = mtd, width = 0.3) +
    xlab("") +
    ylab("") +
    scale_fill_manual("", values = c("TRUE" = "grey65", "FALSE" = "grey85"), labels = c("Weekend", "Rotation")) +
    coord_flip() +
    theme_bg(xticks = FALSE, yticks = FALSE) +
    theme(axis.line = element_blank(), legend.position = "bottom")
```


